replicaCount: 1

image:
  repository: savelysivkov/my-nginx
  tag: "1.0.0.main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: ["/"]
  tls: []
